# SPDX-License-Identifier: Apache-2.0
[workspace]
members = [
    "crates/adapter",
    "crates/census",
    "crates/check",
    "crates/cli",
    "crates/doc",
    "crates/generate",
    "crates/graph",
    "crates/hash",
    "crates/lock",
    "crates/mark",
    "crates/meta",
    "crates/query",
    "crates/ref",
    "crates/resolve",
    "crates/scaffold",
    "crates/yaml",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
publish = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
