// SPDX-License-Identifier: Apache-2.0
//! The audit as text.
//!
//! Every section states its population before it states a number, on the rule
//! [`headwater capture`](../../../../docs/spec/03-authoring-and-lifecycle.md#what-the-capture-cost-store-records-and-what-it-refuses-to)
//! already keeps: a figure with no denominator beside it is a figure nobody
//! should cite. The two places that rule bites hardest here are a creator that
//! no relation declares and a rate over an empty population, and both are
//! written out in words rather than printed as a zero.

use crate::{Audit, WAITING};
use std::fmt::Write;

/// A count with its noun, in the number the count calls for.
///
/// Both forms are arguments because one of the three nouns this report uses is
/// `half`. "1 relations" is the kind of line that makes a reader wonder what
/// else the report did not look at, and "2 halfs" is worse.
fn many(count: usize, singular: &str, plural: &str) -> String {
    match count {
        1 => format!("1 {singular}"),
        n => format!("{n} {plural}"),
    }
}

impl Audit {
    pub fn render(&self) -> String {
        let mut out = String::new();
        self.header(&mut out);
        self.creators_section(&mut out);
        self.families_section(&mut out);
        self.facets_section(&mut out);
        self.shelves_section(&mut out);
        self.dwell_section(&mut out);
        self.waiting_section(&mut out);
        out
    }

    fn header(&self, out: &mut String) {
        let _ = writeln!(
            out,
            "taxonomy audit of {} {}",
            self.subject.package, self.subject.version
        );
        let _ = writeln!(out, "  lock {}", self.subject.lock);
        let _ = writeln!(
            out,
            "  at {}, over {} documents and {} declared edge halves",
            self.subject.now, self.documents, self.halves
        );
        let _ = writeln!(
            out,
            "  {} of them are classified, and {} generated by this engine and carrying a declared\n  \
             identity. Both are nodes, so both are here, and a check report counts the first\n  \
             number alone.",
            self.typed, self.generated
        );
        out.push_str(
            "  It measures the schema against the corpus, and every finding here is about\n  \
             the taxonomy. It gates nothing.\n",
        );

        match &self.freshness {
            Some((facet, window)) => {
                let _ = writeln!(
                    out,
                    "  One bar is declared: `{facet}` is stale after {window} days. It is the only\n  \
                     number a declaration states, so it is the only reading below that carries a\n  \
                     finding. Everything else is a distribution, and nothing declares how narrow a\n  \
                     distribution may get before it is a defect."
                );
            }
            None => out.push_str(
                "  No facet declares a staleness window, so this taxonomy states no bar at all and\n  \
                 every reading below is a distribution.\n",
            ),
        }

        let findings = self.findings();
        match findings.is_empty() {
            true => out.push_str("\nfindings\n  none. No relation has a half on a document past the declared window.\n"),
            false => {
                out.push_str("\nfindings\n");
                for reading in findings {
                    let _ = writeln!(
                        out,
                        "  `{}` has {} of {} halves on a document past the declared window",
                        reading.name, reading.expired, reading.halves
                    );
                }
            }
        }
    }

    fn creators_section(&self, out: &mut String) {
        out.push_str("\nrelations, by the creator each one declares\n");
        out.push_str(
            "  Q4 keeps `created_by` on the relation type, so every row is a relation and never\n  \
             an edge instance. Two halves of one relation carry one value whatever wrote them.\n  \
             `captured` is the share of eligible documents that declared at least one half.\n",
        );

        for (creator, readings) in &self.creators.by_creator {
            if readings.is_empty() {
                let _ = writeln!(out, "  {creator} — no relation declares it");
                continue;
            }
            let halves: usize = readings.iter().map(|reading| reading.halves).sum();
            let _ = writeln!(
                out,
                "  {creator} — {}, {halves} of {} halves",
                many(readings.len(), "relation", "relations"),
                self.halves
            );
            for reading in readings {
                let captured = match reading.capture() {
                    Some(rate) => format!("{rate:.1}% captured"),
                    None => "no eligible document".to_string(),
                };
                let _ = writeln!(
                    out,
                    "    {:<16} {:>10}, {:3} eligible, {:3} declaring, {captured}",
                    reading.name,
                    many(reading.halves, "half", "halves"),
                    reading.eligible,
                    reading.participating
                );
                let _ = writeln!(
                    out,
                    "                     {} past the window, {} on a document with no readable date",
                    reading.expired, reading.undated
                );
            }
        }

        if !self.creators.undeclared.is_empty() {
            out.push_str("  no creator declared\n");
            for reading in &self.creators.undeclared {
                let _ = writeln!(out, "    {}", reading.name);
            }
        }

        let absent = self.creators.absent();
        if !absent.is_empty() {
            let _ = writeln!(
                out,
                "  {} of the 6 creators spec 2 declares have no relation in this taxonomy: {}.",
                absent.len(),
                absent.join(", ")
            );
            out.push_str(
                "  A comparison against any of them has one arm over this corpus, and the missing\n  \
                 arm is a property of the taxonomy rather than of the authoring. No number below\n  \
                 stands in for one.\n",
            );
        }
    }

    fn families_section(&self, out: &mut String) {
        out.push_str("\nrelation families\n");
        let mut overrides = 0;
        for reading in &self.families {
            let _ = writeln!(
                out,
                "  {:<12} {}, {}",
                reading.family,
                many(reading.relations, "relation", "relations"),
                many(reading.halves, "half", "halves")
            );
            for (relation, declared, default) in &reading.overrides {
                overrides += 1;
                let _ = writeln!(
                    out,
                    "    `{relation}` declares {declared}, and the family gives {default}"
                );
            }
            for relation in &reading.restatements {
                let _ = writeln!(
                    out,
                    "    `{relation}` declares the nuclearity the family already gives"
                );
            }
        }
        if overrides == 0 {
            out.push_str("  no relation contradicts the nuclearity its family gives.\n");
        }
    }

    fn facets_section(&self, out: &mut String) {
        out.push_str("\nfacets, and what each one separates\n");
        for reading in &self.facets {
            let role = match &reading.role {
                Some(role) => format!("role {role}"),
                None => "no role".to_string(),
            };
            let declared = match reading.declared_values {
                0 => "no declared set".to_string(),
                n => format!("{n} declared"),
            };
            let _ = writeln!(
                out,
                "  {:<14} {role}, {declared}, {} of {} documents carry it",
                reading.name, reading.carried_by, self.documents
            );
            // A facet whose every carrier holds a different value is the case
            // where a commonest value says nothing, and printing one would put
            // a line of somebody's prose into a report about the schema. What
            // the reading is actually for is the concentration, and at one
            // document per value there is none.
            if reading.carried_by == 0 {
                out.push_str(
                    "                 no document carries it, so it separates nothing here\n",
                );
                continue;
            }
            match (&reading.commonest, reading.concentration()) {
                (Some((value, count)), Some(share)) if *count > 1 => {
                    let _ = writeln!(
                        out,
                        "                 {} distinct values in use, commonest `{value}` on {count}, {share:.1}%",
                        reading.distinct
                    );
                }
                _ => {
                    let _ = writeln!(
                        out,
                        "                 {} distinct values in use, and no two documents share one",
                        reading.distinct
                    );
                }
            }
        }
        out.push_str("  A facet whose documents nearly all share one value separates nearly nothing.\n  \
                      Nothing declares where that line is, so the share above carries no verdict.\n");

        match self.dependences.is_empty() {
            true => out.push_str(
                "  No declared value set fixes another over this corpus, so no pair of them is\n  \
                 redundant on the evidence here.\n",
            ),
            false => {
                out.push_str("  pairs where one value fixes the other\n");
                for pair in &self.dependences {
                    let _ = writeln!(
                        out,
                        "    `{}` fixes `{}` over the {} documents that carry both",
                        pair.determines, pair.determined, pair.over
                    );
                }
            }
        }
    }

    fn shelves_section(&self, out: &mut String) {
        out.push_str("\nshelves that hold several kinds\n");
        if self.shelves.is_empty() {
            out.push_str("  none. Every shelf this taxonomy declares holds one kind.\n");
            return;
        }
        out.push_str(
            "  The discriminator is self-asserted, and kind decides every obligation after it.\n  \
             A shelf that drifts toward its cheapest kind is what this reading shows.\n",
        );
        for reading in &self.shelves {
            let _ = writeln!(
                out,
                "  {} — discriminator `{}`, {}",
                reading.shelf,
                reading.discriminator,
                many(reading.documents, "document", "documents")
            );
            for (kind, count) in &reading.kinds {
                let _ = writeln!(out, "    {count:5} {kind}");
            }
        }
    }

    fn dwell_section(&self, out: &mut String) {
        out.push_str("\ndwell in the current state\n");
        if self.dwell.is_empty() {
            out.push_str(
                "  no reading. It needs a facet in the `state` role and one in `state_entered`,\n  \
                 and this taxonomy declares fewer than both.\n",
            );
            return;
        }
        out.push_str("  Observed and never policed. A state nothing sits in has a row too.\n");
        for reading in &self.dwell {
            match (reading.days.first(), reading.days.last(), reading.median()) {
                (Some(first), Some(last), Some(median)) => {
                    let _ = writeln!(
                        out,
                        "  {:<14} {:>13}, {first} to {last} days, median {median}",
                        reading.state,
                        many(reading.documents, "document", "documents")
                    );
                }
                _ => {
                    let _ = writeln!(
                        out,
                        "  {:<14} {:>13}, and no dwell reading",
                        reading.state,
                        many(reading.documents, "document", "documents")
                    );
                }
            }
            if reading.undated > 0 {
                let _ = writeln!(
                    out,
                    "                 {} with no readable entry date",
                    reading.undated
                );
            }
        }
    }

    fn waiting_section(&self, out: &mut String) {
        out.push_str("\nwhat this verb does not measure, and what each one waits on\n");
        for waiting in WAITING {
            let _ = writeln!(out, "  {} — {}", waiting.reading, waiting.waits_on);
        }
    }
}
