// SPDX-License-Identifier: Apache-2.0
//! The audit as text.
//!
//! Every section states its population before it states a number, on the rule
//! [`headwater capture`](../../../../docs/spec/03-authoring-and-lifecycle.md#what-the-capture-cost-store-records-and-what-it-refuses-to)
//! already keeps: a figure with no denominator beside it is a figure nobody
//! should cite. The two places that rule bites hardest here are a creator that
//! no relation declares and a rate over an empty population, and both are
//! written out in words rather than printed as a zero.

use crate::Audit;
use headwater_check::filled;
use headwater_check::paint::{paint, ColorMode, Role};
use std::fmt::Write;

/// A token painted into text that is already folded.
///
/// [`filled`] measures a line in characters, and an SGR sequence is characters
/// that occupy no column. A token painted before the fold therefore spends nine
/// characters of the line's budget on bytes a terminal never shows, and every
/// break after it lands early. Compose plain, fold, then substitute here.
///
/// The token is a single word with no space in it, so the word-boundary fold
/// never splits one and the substitution always finds it whole. That is the
/// same condition `headwater_adapter::text` states for its own color words.
fn painted_in_place(folded: &str, token: &str, role: Role, mode: ColorMode) -> String {
    match mode {
        ColorMode::Plain => folded.to_string(),
        ColorMode::Ansi => folded.replace(token, &paint(role, token, mode)),
    }
}

/// A count with its noun, in the number the count calls for.
///
/// Both forms are arguments because one of the three nouns this report uses is
/// `half`. "1 relations" is the kind of line that makes a reader wonder what
/// else the report did not look at, and "2 halfs" is worse.
fn many(count: usize, singular: &str, plural: &str) -> String {
    match count {
        1 => format!("1 {singular}"),
        n => format!("{n} {plural}"),
    }
}

impl Audit {
    /// The report, rendered in the mode the caller sensed for its stream.
    ///
    /// `mode` is a parameter and never a read, so this crate holds no opinion
    /// about whether anything is a terminal. Every `--format json` path, the
    /// MCP tool and every test state [`ColorMode::Plain`], and the one human
    /// call site in `headwater_cli` states `stdout_color()`.
    pub fn render(&self, mode: ColorMode) -> String {
        let mut out = String::new();
        self.header(&mut out, mode);
        self.creators_section(&mut out, mode);
        self.families_section(&mut out, mode);
        self.facets_section(&mut out, mode);
        self.shelves_section(&mut out, mode);
        self.layouts_section(&mut out, mode);
        self.dwell_section(&mut out, mode);
        self.warrants_section(&mut out, mode);
        self.adoption_section(&mut out, mode);
        self.waiting_section(&mut out, mode);
        out
    }

    fn header(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "{} {} {}",
            paint(Role::Heading, "taxonomy audit of", mode),
            self.subject.package,
            self.subject.version
        );
        let _ = writeln!(out, "  lock {}", self.subject.lock);
        let _ = writeln!(
            out,
            "  at {}, over {} documents and {} declared edge halves",
            self.subject.now, self.documents, self.halves
        );
        let _ = writeln!(
            out,
            "  {} of them are classified, and {} generated by this engine and carrying a declared\n  \
             identity. Both are nodes, so both are here, and a check report counts the first\n  \
             number alone.",
            self.typed, self.generated
        );
        out.push_str(
            "  It measures the schema against the corpus, and every finding here is about\n  \
             the taxonomy. It gates nothing.\n",
        );

        match &self.freshness {
            Some((facet, window)) => {
                let _ = writeln!(
                    out,
                    "  One bar is declared: `{facet}` is stale after {window} days. It is the only\n  \
                     number a declaration states, so it is the only reading below that carries a\n  \
                     finding. Everything else is a distribution, and nothing declares how narrow a\n  \
                     distribution may get before it is a defect."
                );
            }
            None => out.push_str(
                "  No facet declares a staleness window, so this taxonomy states no bar at all and\n  \
                 every reading below is a distribution.\n",
            ),
        }

        let findings = self.findings();
        match findings.is_empty() {
            true => {
                let _ = writeln!(
                    out,
                    "\n{}\n  none. No relation has a half on a document past the declared window.",
                    paint(Role::Heading, "findings", mode)
                );
            }
            false => {
                let _ = writeln!(out, "\n{}", paint(Role::Heading, "findings", mode));
                for reading in findings {
                    let _ = writeln!(
                        out,
                        "  `{}` has {} of {} halves on a document past the declared window",
                        reading.name, reading.expired, reading.halves
                    );
                }
            }
        }
    }

    fn creators_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(
                Role::Heading,
                "relations, by the creator each one declares",
                mode
            )
        );
        out.push_str(
            "  Q4 keeps `created_by` on the relation type, so every row is a relation and never\n  \
             an edge instance. Two halves of one relation carry one value whatever wrote them.\n  \
             `captured` is the share of eligible documents that declared at least one half.\n",
        );

        for (creator, readings) in &self.creators.by_creator {
            if readings.is_empty() {
                let _ = writeln!(out, "  {creator} — no relation declares it");
                continue;
            }
            let halves: usize = readings.iter().map(|reading| reading.halves).sum();
            let _ = writeln!(
                out,
                "  {creator} — {}, {halves} of {} halves",
                many(readings.len(), "relation", "relations"),
                self.halves
            );
            for reading in readings {
                let captured = match reading.capture() {
                    Some(rate) => format!("{rate:.1}% captured"),
                    None => "no eligible document".to_string(),
                };
                let _ = writeln!(
                    out,
                    "    {:<16} {:>10}, {:3} eligible, {:3} declaring, {captured}",
                    reading.name,
                    many(reading.halves, "half", "halves"),
                    reading.eligible,
                    reading.participating
                );
                let _ = writeln!(
                    out,
                    "                     {} past the window, {} on a document with no readable date",
                    reading.expired, reading.undated
                );
            }
        }

        if !self.creators.undeclared.is_empty() {
            out.push_str("  no creator declared\n");
            for reading in &self.creators.undeclared {
                let _ = writeln!(out, "    {}", reading.name);
            }
        }

        let absent = self.creators.absent();
        if !absent.is_empty() {
            let _ = writeln!(
                out,
                "  {} of the 6 creators spec 2 declares have no relation in this taxonomy: {}.",
                absent.len(),
                absent.join(", ")
            );
            out.push_str(
                "  A comparison against any of them has one arm over this corpus, and the missing\n  \
                 arm is a property of the taxonomy rather than of the authoring. No number below\n  \
                 stands in for one.\n",
            );
        }
    }

    fn families_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(out, "\n{}", paint(Role::Heading, "relation families", mode));
        let mut overrides = 0;
        for reading in &self.families {
            let _ = writeln!(
                out,
                "  {:<12} {}, {}",
                reading.family,
                many(reading.relations, "relation", "relations"),
                many(reading.halves, "half", "halves")
            );
            for (relation, declared, default) in &reading.overrides {
                overrides += 1;
                let _ = writeln!(
                    out,
                    "    `{relation}` declares {declared}, and the family gives {default}"
                );
            }
            for relation in &reading.restatements {
                let _ = writeln!(
                    out,
                    "    `{relation}` declares the nuclearity the family already gives"
                );
            }
        }
        if overrides == 0 {
            out.push_str("  no relation contradicts the nuclearity its family gives.\n");
        }
    }

    fn facets_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(Role::Heading, "facets, and what each one separates", mode)
        );
        for reading in &self.facets {
            let role = match &reading.role {
                Some(role) => format!("role {role}"),
                None => "no role".to_string(),
            };
            let declared = match reading.declared_values {
                0 => "no declared set".to_string(),
                n => format!("{n} declared"),
            };
            let _ = writeln!(
                out,
                "  {:<14} {role}, {declared}, {} of {} documents carry it",
                reading.name, reading.carried_by, self.documents
            );
            // A facet whose every carrier holds a different value is the case
            // where a commonest value says nothing, and printing one would put
            // a line of somebody's prose into a report about the schema. What
            // the reading is actually for is the concentration, and at one
            // document per value there is none.
            if reading.carried_by == 0 {
                out.push_str(
                    "                 no document carries it, so it separates nothing here\n",
                );
                continue;
            }
            match (&reading.commonest, reading.concentration()) {
                (Some((value, count)), Some(share)) if *count > 1 => {
                    let _ = writeln!(
                        out,
                        "                 {} distinct values in use, commonest `{value}` on {count}, {share:.1}%",
                        reading.distinct
                    );
                }
                _ => {
                    let _ = writeln!(
                        out,
                        "                 {} distinct values in use, and no two documents share one",
                        reading.distinct
                    );
                }
            }
        }
        out.push_str("  A facet whose documents nearly all share one value separates nearly nothing.\n  \
                      Nothing declares where that line is, so the share above carries no verdict.\n");

        match self.dependences.is_empty() {
            true => out.push_str(
                "  No declared value set fixes another over this corpus, so no pair of them is\n  \
                 redundant on the evidence here.\n",
            ),
            false => {
                out.push_str("  pairs where one value fixes the other\n");
                for pair in &self.dependences {
                    let _ = writeln!(
                        out,
                        "    `{}` fixes `{}` over the {} documents that carry both",
                        pair.determines, pair.determined, pair.over
                    );
                }
            }
        }
    }

    fn shelves_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(Role::Heading, "shelves that hold several kinds", mode)
        );
        if self.shelves.is_empty() {
            out.push_str("  none. Every shelf this taxonomy declares holds one kind.\n");
            return;
        }
        out.push_str(
            "  The discriminator is self-asserted, and kind decides every obligation after it.\n  \
             A shelf that drifts toward its cheapest kind is what this reading shows.\n",
        );
        for reading in &self.shelves {
            let _ = writeln!(
                out,
                "  {} — discriminator `{}`, {}",
                reading.shelf,
                reading.discriminator,
                many(reading.documents, "document", "documents")
            );
            for (kind, count) in &reading.kinds {
                let _ = writeln!(out, "    {count:5} {kind}");
            }
        }
    }

    /// How far the file names on each shelf have drifted from the layout that
    /// named them at birth.
    ///
    /// The denominator is the measurable population and never the shelf, which
    /// is the whole reason this reading carries a [`Supply`] per row. A shelf
    /// whose kind declares no source for a placeholder cannot be measured at
    /// all, and a report that counted those documents as disagreeing would
    /// state an authoring failure where a declaration is missing.
    ///
    /// [`Supply`]: crate::Supply
    fn layouts_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(
                Role::Heading,
                "file names, against the layout each shelf declares",
                mode
            )
        );
        if self.layouts.is_empty() {
            out.push_str(
                "  none. No shelf of this taxonomy declares a layout, so nothing names a\n  \
                          file and no name can disagree.\n",
            );
            return;
        }
        out.push_str(
            "  A layout names a file at birth and no check reads one afterwards, so this is a\n  \
             convention rather than a rule. A generated document is excluded: its name is the\n  \
             emitter's, as its content is.\n",
        );
        for reading in &self.layouts {
            let _ = writeln!(
                out,
                "  {} — `{}`, {}",
                reading.shelf,
                paint(Role::Path, &reading.layout, mode),
                many(reading.identified, "document", "documents")
            );
            // Folded first and painted afterwards. `says()` quotes the layout
            // inside the prose it folds, so a paint that ran before this call
            // would move every break after the layout name six characters
            // left, and the fifth arm of `tools/color-fixtures.sh` is what
            // sees that.
            let folded = filled(
                &format!(
                    "      {} — {}\n",
                    reading.adherence.located(),
                    reading.adherence.says()
                ),
                headwater_check::fill::WIDTH,
            );
            out.push_str(&painted_in_place(
                &folded,
                &reading.layout,
                Role::Path,
                mode,
            ));
        }
        let measured: usize = self.layouts.iter().map(|reading| reading.measured).sum();
        let renders: usize = self.layouts.iter().map(|reading| reading.renders).sum();
        let identified: usize = self.layouts.iter().map(|reading| reading.identified).sum();
        let _ = writeln!(
            out,
            "  A layout renders the name of {renders} of the {measured} measurable documents, over\n  \
             {identified} standing on a shelf that declares one. Nothing states how far a shelf may\n  \
             drift, so the figure carries no verdict."
        );
    }

    fn dwell_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(Role::Heading, "dwell in the current state", mode)
        );
        if self.dwell.is_empty() {
            out.push_str(
                "  no reading. It needs a facet in the `state` role and one in `state_entered`,\n  \
                 and this taxonomy declares fewer than both.\n",
            );
            return;
        }
        out.push_str("  Observed and never policed. A state nothing sits in has a row too.\n");
        for reading in &self.dwell {
            match (reading.days.first(), reading.days.last(), reading.median()) {
                (Some(first), Some(last), Some(median)) => {
                    let _ = writeln!(
                        out,
                        "  {:<14} {:>13}, {first} to {last} days, median {median}",
                        reading.state,
                        many(reading.documents, "document", "documents")
                    );
                }
                _ => {
                    let _ = writeln!(
                        out,
                        "  {:<14} {:>13}, and no dwell reading",
                        reading.state,
                        many(reading.documents, "document", "documents")
                    );
                }
            }
            if reading.undated > 0 {
                let _ = writeln!(
                    out,
                    "                 {} with no readable entry date",
                    reading.undated
                );
            }
        }
    }

    /// The warrant distribution, and the promotion denominator inside it.
    ///
    /// The closed set is walked in full, so a value nobody wrote has a row and
    /// a reader can tell an empty arm from an absent one. Two of the four rows
    /// stand at zero by construction rather than for want of authoring, and
    /// the row says so instead of leaving a reader to work it out.
    fn warrants_section(&self, out: &mut String, mode: ColorMode) {
        let warrants = &self.warrants;
        let _ = writeln!(
            out,
            "\n{}",
            paint(
                Role::Heading,
                "warrants, over the closed set spec 3 declares",
                mode
            )
        );
        out.push_str(
            "  A warrant states what stands behind a document, and promotion is the act that\n  \
             moves one from `asserted` to `accepted`. The set is closed, so every value has a\n  \
             row whether a document of this corpus states it or not.\n",
        );
        for reading in &warrants.readings {
            if !reading.closed_set {
                continue;
            }
            let note = match (reading.derived, reading.stated) {
                (true, _) => "the engine reads this off the generated-file marker",
                (false, 0) => "no document of this corpus states it",
                (false, _) => "",
            };
            let row = format!("  {:5} {:<14}{note}", reading.stated, reading.value);
            let _ = writeln!(out, "{}", row.trim_end());
        }
        let _ = writeln!(
            out,
            "  Stated on {} of {}, and absent on {}. Spec 3 makes the value required, so the\n  second figure is a population and never a default. The census reported {} of these rows\n  as generated, and the engine reads the warrant of a generated document off the marker\n  rather than out of a declaration.",
            warrants.stated(),
            self.documents,
            warrants.unstated,
            warrants.generated
        );

        let outside = warrants.outside();
        match outside.is_empty() {
            true => out.push_str("  Every value in use is one the closed set holds.\n"),
            false => {
                out.push_str(
                    "  Values the closed set does not hold, each with the count that states it. No\n  check of this engine reads a warrant value, so this is the only line that reports one:\n",
                );
                for reading in outside {
                    let _ = writeln!(out, "    {:5} `{}`", reading.stated, reading.value);
                }
            }
        }

        let _ = writeln!(
            out,
            "  The `asserted` population is {}, which is the denominator a promotion rate divides\n  by. The numerator is a count per change, which `headwater check --change` reports under\n  `warrant.promoted`: this verb reads one working tree, so it holds one half of that rate\n  and can never reach the other. Nothing declares how many promotions in one change is too\n  many, so no figure here carries a verdict.",
            warrants.asserted()
        );
    }

    /// The adoption payload of this run, against every reading the store holds.
    ///
    /// It sits after the warrants and before the waits because it is a reading
    /// this verb **takes**, and the waits are what it does not take. What this
    /// verb cannot do is state a trend from one reading, and the section says
    /// that in its own words rather than becoming a fourth `Supply` arm.
    fn adoption_section(&self, out: &mut String, mode: ColorMode) {
        let series = &self.adoption;
        let recorded = &series.recorded;
        let _ = writeln!(
            out,
            "\n{}",
            paint(Role::Heading, "adoption payload decay", mode)
        );
        out.push_str(
            "  The store is `.headwater/adoption.jsonl`, which is outside the corpus root. No\n  \
             census row covers it, no language regime binds it, and no rule reads it. No crate\n  \
             of this engine walks git history, so a series exists only where a run was handed\n  \
             one reading at a time.\n",
        );

        match crate::reading::span(recorded) {
            None => out.push_str(
                "  no reading recorded, so there is no series. `taxonomy audit --record` takes the first one\n",
            ),
            Some((first, last)) => {
                let digests = crate::reading::locks(recorded).len();
                let _ = writeln!(
                    out,
                    "  {}, {first} to {last}, under {}",
                    many(recorded.len(), "reading", "readings"),
                    many(digests, "taxonomy", "taxonomies")
                );
            }
        }
        for line in &series.unreadable {
            let _ = writeln!(
                out,
                "  line {} of the store is not a reading and is counted nowhere: {}",
                line.line, line.why
            );
        }

        let reading = &series.reading;
        // An empty task list has two causes, and the report may not state the
        // one it did not read. A lock that declares no payload and a lock whose
        // every task this engine refused both arrive here with no task, and the
        // second is the state an adopter has to be told the truth about. The
        // refused count is what tells them apart, and the line below states it.
        match (reading.tasks.is_empty(), reading.refused) {
            (true, 0) => out.push_str(
                "  this run reads no task, because the lock declares no adoption payload\n",
            ),
            (true, _) => out.push_str(
                "  this run reads no task it can measure, and the cause is a refusal rather than an\n  absent payload\n",
            ),
            (false, _) => {
                let _ = writeln!(
                    out,
                    "  this run reads {}, {} open, {} closed, holding {}",
                    many(reading.tasks.len(), "task", "tasks"),
                    many(reading.open(), "pair", "pairs"),
                    reading.closed(),
                    many(reading.held(), "finding", "findings")
                );
            }
        }
        if reading.refused > 0 {
            let _ = writeln!(
                out,
                "  it could not read {}. A refused task is a task nobody is measuring, and a series\n  that dropped one would report a payload shrinking when it went dark",
                many(reading.refused, "task", "tasks")
            );
        }

        for task in &reading.tasks {
            let _ = writeln!(
                out,
                "    {}  open {}, closed {}, holding {}, until {}, {}",
                paint(Role::Obligation, &task.id, mode),
                task.open,
                task.closed,
                many(task.held, "finding", "findings"),
                task.until,
                crate::reading::state_name(task.state)
            );
            let seen = crate::reading::appearances(recorded, &task.id);
            match seen.first().zip(seen.last()) {
                None => out.push_str(
                    "      no recorded reading holds it, so this run is the first sight of it\n",
                ),
                Some((first, last)) if seen.len() == 1 => {
                    let _ = writeln!(
                        out,
                        "      open {} on the one recorded reading that holds it, and {} closed",
                        first.open, last.closed
                    );
                }
                Some((first, last)) => {
                    let _ = writeln!(
                        out,
                        "      open {} on the first of {} readings that hold it, and {} on the last",
                        first.open,
                        seen.len(),
                        last.open
                    );
                }
            }
        }

        let (reached, over) = crate::reading::zeroed(recorded);
        match over {
            0 => out.push_str(
                "  no task has been recorded, so the fraction that reaches zero before its expiry has no\n  denominator yet\n",
            ),
            _ => {
                let _ = writeln!(
                    out,
                    "  payloads at zero before their expiry: {reached} of {} the series has seen.\n  \
                     The denominator is every task identifier the store holds, and never the tasks\n  \
                     the lock declares today: a task that closed and was deleted is a payload that\n  \
                     reached zero",
                    many(over, "task", "tasks")
                );
            }
        }

        let digests = crate::reading::locks(recorded);
        if digests.len() > 1 {
            let _ = writeln!(
                out,
                "  {} produced these readings, so the figures above are across {} denominators and\n  \
                 are not a trend. A rule the taxonomy stopped running closes a pair with no change\n  \
                 in what anybody wrote, so two readings under two digests are two measurements",
                many(digests.len(), "taxonomy", "taxonomies"),
                digests.len()
            );
            for digest in &digests {
                let _ = writeln!(out, "    {digest}");
            }
        }
        match recorded.len() {
            0 => out.push_str(
                "  A payload with no reading behind it has no history, and the elapsed time between\n  two readings is the one quantity no engine can supply.\n",
            ),
            1 => out.push_str(
                "  A series of one reading states a value and never a trend.\n",
            ),
            _ => {}
        }
    }

    /// What this verb does not measure, as this run found each prerequisite.
    ///
    /// The three readings were three string literals until the promotion wait
    /// went false underneath one and nothing reported it. Each prerequisite is
    /// now evaluated against the corpus in front of the run, and each one names
    /// where its absence lives, because a declaration, an authoring pass and a
    /// decision are three different things to go and do.
    fn waiting_section(&self, out: &mut String, mode: ColorMode) {
        let _ = writeln!(
            out,
            "\n{}",
            paint(
                Role::Heading,
                "what this verb does not measure, and what each one waits on",
                mode
            )
        );
        out.push_str(
            "  Every prerequisite below was evaluated against this corpus on this run, so a\n  wait that a corpus has ended says so with no edit to this engine.\n",
        );
        for waiting in &self.waiting {
            match waiting.waits() {
                true => {
                    let _ = writeln!(out, "  {} — waits", waiting.reading);
                }
                false => {
                    let _ = writeln!(
                        out,
                        "  {} — waits on nothing. Every prerequisite is met and the reading is\n  still not taken, which is a gap in this verb rather than a wait on a\n  corpus.",
                        waiting.reading
                    );
                }
            }
            for need in &waiting.needs {
                let _ = writeln!(out, "    {}", need.needs);
                out.push_str(&filled(
                    &format!("      {} — {}\n", need.supply.located(), need.supply.says()),
                    headwater_check::fill::WIDTH,
                ));
            }
        }
        let waiting = self
            .waiting
            .iter()
            .filter(|reading| reading.waits())
            .count();
        let _ = writeln!(
            out,
            "  {} of {} still wait. Each one states what ends it: a declaration, or an\n  authoring pass over a corpus.",
            waiting,
            self.waiting.len()
        );
    }
}
